### ISSUE TITLE
Implement Feature for Sending Game Scores to ${gameId}-scores.json

### ISSUE THREAD

**Issue by Ooyd** [hp-potion/vsc-gameboy#23]
### Which part does this bug appears?(or the part you guess)

Platform

### Link to the code that reproduces this issue

https://github.com/Ooyd/vsc-gameboy

### To Reproduce

To replicate the issue, please follow these steps:

1. Pull the latest code from the branch: https://github.com/hp-potion/vsc-gameboy/tree/feature/score.
2. Start the application in debug mode.
3. Launch the Tetris game.
4. Click on the 'Send Test Score' button located at the top-left corner. This is a test feature implemented to facilitate the overall functionality.
5. Verify if the global storage file (e.g., C:\Users\User\AppData\Roaming\Code\User\globalStorage\hp-potion.vsc-gameboy) is created correctly and if the scores are appropriately displayed.

### Current vs. Expected behavior

Currently, the score is being generated through the test button. However, there is uncertainty about how to integrate the logic for sending scores from the get-html-content class. Further clarification and guidance on implementing this feature are needed.

### Additional context

Currently, the sidebar for game scores has been implemented and is functional. It updates and displays scores stored in the gameId-scores.json file. 
However, the automatic updating of this file with new scores from games is not yet implemented. This feature is crucial for maintaining an up-to-date and dynamic scoring system within the application.

### Issue Reference
#17

**Comment by junman95** [comment]
It is a good discussion!

Yes, I guess we should provide interface to connect scoring function in each games.
It seems not easy to adapt to all the different scoring functions in every games.
I think you can work on making a `unified interface` to score in globalStorage.
