### ISSUE TITLE
Propose additional features of the github issue template.

### ISSUE THREAD

**Issue by Ooyd** [hp-potion/vsc-gameboy#24]
### Which part does this feature is for?(or the part you guess)

template

### Feature suggestion

It would be nice to have an Issue Reference tab in each template.

### Additional context

I've added a separate photo showing the **current state of our issue templates (for both bug reports and feature requests)** where the **option to reference related issues is missing.** 
I believe this is an important aspect to include, so I've raised it as an issue for consideration."

![image](https://github.com/hp-potion/vsc-gameboy/assets/92978646/275a0b64-78f9-43dd-a6dd-fb01c5a0d359)

**Comment by junman95** [comment]
Sure!
You can work on it.
