### ISSUE TITLE
Webview LifeCycle issue

### ISSUE THREAD

**Issue by junman95** [hp-potion/vsc-gameboy#3]
### Which part does this bug appears?(or the part you guess)

Platform

### To Reproduce

If I click another game from tabs,
past game status resets.

### Current vs. Expected behavior

the status should not be deleted even though I open up a new webview tab.

### Additional context

can be solved if we look into this reference
https://code.visualstudio.com/api/extension-guides/webview#lifecycle

**Comment by Ooyd** [comment]
https://github.com/hp-potion/vsc-gameboy/commit/7f8517ed7462991719b969cdca74f61145761bbf Resolved the issue by managing open webviews efficiently using a Map, ensuring no duplicate panels are created.
