### ISSUE TITLE
Multiple tab creation issue

### ISSUE THREAD

**Issue by junman95** [hp-potion/vsc-gameboy#4]
### Which part does this bug appears?(or the part you guess)

Platform

### To Reproduce

https://github.com/hp-potion/vsc-gameboy/assets/22022776/8848f6da-4eed-4378-abd3-f6dfba521138

every time I click game list, a new tab opens.
It should be blocked and current webview page should be rerendered.

**Comment by Ooyd** [comment]
https://github.com/hp-potion/vsc-gameboy/commit/7f8517ed7462991719b969cdca74f61145761bbf Resolved the tab creation issue by utilizing the retainContextWhenHidden option
